services:
  vectora:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - vectora-data:/data
    stop_grace_period: 10s
    environment:
      - VECTORA_PASSWORD=123

volumes:
  vectora-data:
